# Generated by Django 6.0 on 2025-12-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
